package com.demo.dao;

import com.demo.model.Compress;
import com.demo.model.CompressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    long countByExample(CompressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int deleteByExample(CompressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int insert(Compress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int insertSelective(Compress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    List<Compress> selectByExample(CompressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    Compress selectByPrimaryKey(Integer rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Compress record, @Param("example") CompressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Compress record, @Param("example") CompressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Compress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compress
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Compress record);
}