package com.demo.dao;

import com.demo.model.Details;
import com.demo.model.DetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    long countByExample(DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int deleteByExample(DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int insert(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int insertSelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    List<Details> selectByExample(DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    Details selectByPrimaryKey(Integer rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Details record, @Param("example") DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Details record, @Param("example") DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Details record);
}