package com.demo.dao;

import com.demo.model.Endstatus;
import com.demo.model.EndstatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EndstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endstatus
     *
     * @mbg.generated
     */
    long countByExample(EndstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endstatus
     *
     * @mbg.generated
     */
    int deleteByExample(EndstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endstatus
     *
     * @mbg.generated
     */
    int insert(Endstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endstatus
     *
     * @mbg.generated
     */
    int insertSelective(Endstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endstatus
     *
     * @mbg.generated
     */
    List<Endstatus> selectByExample(EndstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endstatus
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Endstatus record, @Param("example") EndstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endstatus
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Endstatus record, @Param("example") EndstatusExample example);
}