package com.demo.dao;

import com.demo.model.Signals;
import com.demo.model.SignalsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signals
     *
     * @mbg.generated
     */
    long countByExample(SignalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signals
     *
     * @mbg.generated
     */
    int deleteByExample(SignalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signals
     *
     * @mbg.generated
     */
    int insert(Signals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signals
     *
     * @mbg.generated
     */
    int insertSelective(Signals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signals
     *
     * @mbg.generated
     */
    List<Signals> selectByExample(SignalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signals
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Signals record, @Param("example") SignalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signals
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Signals record, @Param("example") SignalsExample example);
}