package com.demo.dao;

import com.demo.model.Standard;
import com.demo.model.StandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    long countByExample(StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int deleteByExample(StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int insert(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int insertSelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    List<Standard> selectByExample(StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    Standard selectByPrimaryKey(Integer rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Standard record, @Param("example") StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Standard record, @Param("example") StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Standard record);
}