package com.demo.dao;

import com.demo.model.Testscore;
import com.demo.model.TestscoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestscoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testscore
     *
     * @mbg.generated
     */
    long countByExample(TestscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testscore
     *
     * @mbg.generated
     */
    int deleteByExample(TestscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testscore
     *
     * @mbg.generated
     */
    int insert(Testscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testscore
     *
     * @mbg.generated
     */
    int insertSelective(Testscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testscore
     *
     * @mbg.generated
     */
    List<Testscore> selectByExample(TestscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testscore
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Testscore record, @Param("example") TestscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testscore
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Testscore record, @Param("example") TestscoreExample example);
}