package com.demo.model;

import java.util.Date;
import java.util.Objects;

public class Compress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compress.row_id
     *
     * @mbg.generated
     */
    private Integer rowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compress.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compress.transdate
     *
     * @mbg.generated
     */
    private Date transdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compress.row_id
     *
     * @return the value of compress.row_id
     *
     * @mbg.generated
     */
    public Integer getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compress.row_id
     *
     * @param rowId the value for compress.row_id
     *
     * @mbg.generated
     */
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compress.currency
     *
     * @return the value of compress.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compress.currency
     *
     * @param currency the value for compress.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compress.transdate
     *
     * @return the value of compress.transdate
     *
     * @mbg.generated
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compress.transdate
     *
     * @param transdate the value for compress.transdate
     *
     * @mbg.generated
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Compress compress = (Compress) o;
        return Objects.equals(currency, compress.currency) &&
                Objects.equals(transdate, compress.transdate);
    }

    @Override
    public int hashCode() {

        return Objects.hash(currency, transdate);
    }

}