package com.demo.model;

import java.util.Date;

public class Details {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.row_id
     *
     * @mbg.generated
     */
    private Integer rowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.cash
     *
     * @mbg.generated
     */
    private String cash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.isfixed
     *
     * @mbg.generated
     */
    private Integer isfixed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.iscompress
     *
     * @mbg.generated
     */
    private Integer iscompress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.trans
     *
     * @mbg.generated
     */
    private Date trans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.transdate
     *
     * @mbg.generated
     */
    private Date transdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.row_id
     *
     * @return the value of details.row_id
     *
     * @mbg.generated
     */
    public Integer getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.row_id
     *
     * @param rowId the value for details.row_id
     *
     * @mbg.generated
     */
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.cash
     *
     * @return the value of details.cash
     *
     * @mbg.generated
     */
    public String getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.cash
     *
     * @param cash the value for details.cash
     *
     * @mbg.generated
     */
    public void setCash(String cash) {
        this.cash = cash == null ? null : cash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.isfixed
     *
     * @return the value of details.isfixed
     *
     * @mbg.generated
     */
    public Integer getIsfixed() {
        return isfixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.isfixed
     *
     * @param isfixed the value for details.isfixed
     *
     * @mbg.generated
     */
    public void setIsfixed(Integer isfixed) {
        this.isfixed = isfixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.iscompress
     *
     * @return the value of details.iscompress
     *
     * @mbg.generated
     */
    public Integer getIscompress() {
        return iscompress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.iscompress
     *
     * @param iscompress the value for details.iscompress
     *
     * @mbg.generated
     */
    public void setIscompress(Integer iscompress) {
        this.iscompress = iscompress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.trans
     *
     * @return the value of details.trans
     *
     * @mbg.generated
     */
    public Date getTrans() {
        return trans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.trans
     *
     * @param trans the value for details.trans
     *
     * @mbg.generated
     */
    public void setTrans(Date trans) {
        this.trans = trans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.currency
     *
     * @return the value of details.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.currency
     *
     * @param currency the value for details.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.transdate
     *
     * @return the value of details.transdate
     *
     * @mbg.generated
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.transdate
     *
     * @param transdate the value for details.transdate
     *
     * @mbg.generated
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }
}