package com.demo.model;

public class Endstatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endstatus.chonggu
     *
     * @mbg.generated
     */
    private String chonggu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endstatus.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endstatus.chongstatus
     *
     * @mbg.generated
     */
    private Integer chongstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endstatus.tuistatus
     *
     * @mbg.generated
     */
    private Integer tuistatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endstatus.issave
     *
     * @mbg.generated
     */
    private Integer issave;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endstatus.chonggu
     *
     * @return the value of endstatus.chonggu
     *
     * @mbg.generated
     */
    public String getChonggu() {
        return chonggu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endstatus.chonggu
     *
     * @param chonggu the value for endstatus.chonggu
     *
     * @mbg.generated
     */
    public void setChonggu(String chonggu) {
        this.chonggu = chonggu == null ? null : chonggu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endstatus.price
     *
     * @return the value of endstatus.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endstatus.price
     *
     * @param price the value for endstatus.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endstatus.chongstatus
     *
     * @return the value of endstatus.chongstatus
     *
     * @mbg.generated
     */
    public Integer getChongstatus() {
        return chongstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endstatus.chongstatus
     *
     * @param chongstatus the value for endstatus.chongstatus
     *
     * @mbg.generated
     */
    public void setChongstatus(Integer chongstatus) {
        this.chongstatus = chongstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endstatus.tuistatus
     *
     * @return the value of endstatus.tuistatus
     *
     * @mbg.generated
     */
    public Integer getTuistatus() {
        return tuistatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endstatus.tuistatus
     *
     * @param tuistatus the value for endstatus.tuistatus
     *
     * @mbg.generated
     */
    public void setTuistatus(Integer tuistatus) {
        this.tuistatus = tuistatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endstatus.issave
     *
     * @return the value of endstatus.issave
     *
     * @mbg.generated
     */
    public Integer getIssave() {
        return issave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endstatus.issave
     *
     * @param issave the value for endstatus.issave
     *
     * @mbg.generated
     */
    public void setIssave(Integer issave) {
        this.issave = issave;
    }
}