package com.demo.model;

import java.util.Date;

public class Signals {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signals.style
     *
     * @mbg.generated
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signals.information
     *
     * @mbg.generated
     */
    private String information;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signals.price
     *
     * @mbg.generated
     */
    private Date price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signals.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signals.style
     *
     * @return the value of signals.style
     *
     * @mbg.generated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signals.style
     *
     * @param style the value for signals.style
     *
     * @mbg.generated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signals.information
     *
     * @return the value of signals.information
     *
     * @mbg.generated
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signals.information
     *
     * @param information the value for signals.information
     *
     * @mbg.generated
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signals.price
     *
     * @return the value of signals.price
     *
     * @mbg.generated
     */
    public Date getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signals.price
     *
     * @param price the value for signals.price
     *
     * @mbg.generated
     */
    public void setPrice(Date price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signals.status
     *
     * @return the value of signals.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signals.status
     *
     * @param status the value for signals.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}