package com.demo.model;

import java.util.Date;

public class Standard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.row_id
     *
     * @mbg.generated
     */
    private Integer rowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.transdate
     *
     * @mbg.generated
     */
    private Date transdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.typeof
     *
     * @mbg.generated
     */
    private String typeof;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.row_id
     *
     * @return the value of standard.row_id
     *
     * @mbg.generated
     */
    public Integer getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.row_id
     *
     * @param rowId the value for standard.row_id
     *
     * @mbg.generated
     */
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.currency
     *
     * @return the value of standard.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.currency
     *
     * @param currency the value for standard.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.transdate
     *
     * @return the value of standard.transdate
     *
     * @mbg.generated
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.transdate
     *
     * @param transdate the value for standard.transdate
     *
     * @mbg.generated
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.typeof
     *
     * @return the value of standard.typeof
     *
     * @mbg.generated
     */
    public String getTypeof() {
        return typeof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.typeof
     *
     * @param typeof the value for standard.typeof
     *
     * @mbg.generated
     */
    public void setTypeof(String typeof) {
        this.typeof = typeof == null ? null : typeof.trim();
    }
}